"""Labeling schemes ("taxonomies") and the labeling prompt.

A taxonomy is the list of aspects worth tracking for one product category, each tied
to the team that would act on it. Tea uses a hand-written taxonomy (built from my own
tea e-commerce experience); every other category gets one generated by the LLM
(see generate_taxonomy.py), so the tool works for laptops, fruit, clothing, etc.
"""
from __future__ import annotations

import json
from pathlib import Path

import config

SENTIMENTS = ("positive", "neutral", "negative")
REPURCHASE = ("yes", "no", "unclear")

TEA_TAXONOMY = {
    "category": "Tea",
    "source": "hand-written",
    "aspects": [
        {"key": "taste", "label_en": "Taste", "label_zh": "口感", "owner": "Product / Sourcing",
         "description": "flavor, strength, bitterness, sweetness"},
        {"key": "aroma", "label_en": "Aroma", "label_zh": "香气", "owner": "Product / Sourcing",
         "description": "smell of dry leaves or brewed tea"},
        {"key": "freshness_quality", "label_en": "Freshness & quality", "label_zh": "新鲜度与品质",
         "owner": "Supply chain / QC",
         "description": "freshness, stale, leaf quality, dust/fannings, consistency between batches"},
        {"key": "packaging", "label_en": "Packaging", "label_zh": "包装", "owner": "Packaging",
         "description": "bags, tins, seals, individual wrapping, damaged packaging, eco concerns"},
        {"key": "price_value", "label_en": "Price & value", "label_zh": "价格与性价比", "owner": "Pricing",
         "description": "price, value for money, cheaper elsewhere, subscribe & save"},
        {"key": "brewing_convenience", "label_en": "Brewing & convenience", "label_zh": "冲泡与便利",
         "owner": "Product / Content",
         "description": "easy to brew, bag breaks, instructions, steeping time, iced tea use"},
        {"key": "health_wellness", "label_en": "Health & wellness", "label_zh": "健康功效", "owner": "Marketing claims",
         "description": "health benefits, digestion, sleep, calming, sugar/calories, ingredients"},
        {"key": "caffeine_energy", "label_en": "Caffeine & energy", "label_zh": "咖啡因与提神",
         "owner": "Product / Content", "description": "caffeine level, energy, jitters, decaf"},
        {"key": "delivery", "label_en": "Delivery", "label_zh": "物流", "owner": "Logistics",
         "description": "shipping speed, arrived damaged, wrong item, quantity received"},
        {"key": "listing_accuracy", "label_en": "Listing accuracy", "label_zh": "描述相符", "owner": "Listing / Content",
         "description": "matches description/photos, size or count different than expected, misleading claims"},
    ],
}


def taxonomy_path(dataset: str, category: str) -> Path:
    return config.TAXONOMY_DIR / f"{dataset}__{category}.json"


def load_taxonomy(dataset: str, category: str) -> dict:
    p = taxonomy_path(dataset, category)
    if p.exists():
        return json.loads(p.read_text())
    if category.lower() == "tea":
        save_taxonomy(dataset, category, TEA_TAXONOMY)
        return TEA_TAXONOMY
    raise FileNotFoundError(
        f"No taxonomy for {dataset}/{category}. Run: python src/generate_taxonomy.py --dataset {dataset}"
    )


def save_taxonomy(dataset: str, category: str, tax: dict) -> None:
    taxonomy_path(dataset, category).write_text(json.dumps(tax, indent=2, ensure_ascii=False))


def aspect_keys(tax: dict) -> list[str]:
    return [a["key"] for a in tax["aspects"]]


def build_system_prompt(tax: dict, language: str, has_rating: bool) -> str:
    aspects = "\n".join(f"- {a['key']}: {a['description']}" for a in tax["aspects"])
    lang_rule = (
        'Write "root_cause" in Simplified Chinese. Copy "evidence" exactly from the review (Chinese).'
        if language == "zh" else
        'Write "root_cause" in English. Copy "evidence" exactly from the review.'
    )
    star_rule = "- Judge sentiment from the text, not only the star rating.\n" if has_rating else ""
    return f"""You are an e-commerce review analyst. Product category: {tax['category']}.
For EACH review, extract structured insight an operations team can act on.

Aspects (use these keys only):
{aspects}

Rules:
- Only tag an aspect if the review actually talks about it. Do not guess.
- "evidence" is a short exact phrase copied from the review (max 12 words / 20 Chinese characters).
- "root_cause" only for negative reviews: one short sentence on the most likely underlying problem, else null.
- "repurchase": be strict, this is used to estimate loyalty.
  "yes" ONLY if the text explicitly says they bought it again, reordered, subscribed, stocked up, or will buy again.
  "no" ONLY if it explicitly says they won't buy again / are returning it / switching / tells others not to buy.
  Praise or complaints alone are "unclear".
- "overall_sentiment": the reviewer's overall verdict on the purchase. Use "neutral" only when it is truly mixed or has no opinion.
{star_rule}- {lang_rule}

Return JSON exactly like:
{{"results": [
  {{"review_id": 123,
    "overall_sentiment": "positive|neutral|negative",
    "aspects": [{{"aspect": "{tax['aspects'][0]['key']}", "sentiment": "positive|neutral|negative", "evidence": "..."}}],
    "root_cause": null,
    "repurchase": "yes|no|unclear"}}
]}}
One result per input review, same review_id."""
